title: D Bhanu Prakash
logo: /fig/Bhanu.png
email: dbhanuprakash233@gmail.com
description: >- 
  Hi there! 
  Thanks for stopping by.
  I invite you to explore my website and the fascinating research, join the conversation, and collaborate on projects
  that hold the promise of shaping a better tomorrow.
baseurl: "/dbhanuprakash233.github.io" # the subpath of your site, e.g. /blog
url: "https://dbhanuprakash233.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dnvbprakash
github_username: dbhanuprakash233

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
